name: lecture-python
channels:
  - default
dependencies:
  - python=3.8
  - anaconda
  - pip
  - pip:
    - jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - quantecon-book-theme
    - sphinx-exercise
    - sphinx-tojupyter

